### ISSUE TITLE
Crash during ui.show()

### ISSUE THREAD

**Issue by halindrome** [w3c/respec#952]
Members of the APA / ARIA and Dpub working groups independently reported that respec based specs are not loading from github - or at least not reliably. When attempting to investigate, it seems the sourcemap is not loading in firefox AND FF is reporting a runtime error so respec is not processing.

An example spec is at https://w3c.github.io/dpub-pwp-ucr/

This seems to load fine in Chrome, but fails in FF and Opera.  Debug window shows a 403 on respec itself in some instances, but it is not clear why.

@marcoscaceres can you please investigate?  @deniak and @tripu do you have anything you want to add?

**Comment by azaroth42** [comment]
Also down for me:

```
respec-w3c-common.build.js.map:32747 Uncaught ReferenceError: buttonCSS is not defined
```

**Comment by marcoscaceres** [comment]
@halindrome, it seems there some issue with rdisplay.js, but that's not part of ReSpec?

**Comment by marcoscaceres** [comment]
@azaroth42, do you have a pointer to your spec?

**Comment by halindrome** [comment]
There are a bunch of specs that were failing to load in ReSpec last week in Safari and Opera.  Examples include the one referenced above, the dpub-aria spec, the aria 1.1 spec, and others.  When we attempted to diagnost the problem, the source map refused to load in firefox and opera.  I had hoped @tobie and @deniak could say more, since they were the ones that discovered this particular problem and I don't have firefox nor opera on my Chromebook (obviously).

**Comment by tobie** [comment]
That wasn't me. :)

**Comment by marcoscaceres** [comment]
@halindrome, it's really odd... I can see the error in the built version, but then I try the built version locally and I don't get the error. It works fine. 

You are right about the source map file, nonetheless... that's also really odd.

**Comment by marcoscaceres** [comment]
@halindrome, ok, seems to be working.... @azaroth42, I owe you a 🍺.

**Comment by azaroth42** [comment]
I just grabbed a 5.x release and ran everything locally to move forwards (thanks to @bigbluehat for the idea).  

https://github.com/w3c/web-annotation/pull/370

**Comment by marcoscaceres** [comment]
@azaroth42, 6.x should be working now if you want to try to switch back.

**Comment by iherman** [comment]
@marcoscaceres, @azaroth42 is currently busy (and, I presume, also sleeping right now:-), but I did switch back for the documents he was editing and it indeed works.

**Comment by tripu** [comment]
Loading [`https://w3c.github.io/dpub-pwp-ucr/`](https://w3c.github.io/dpub-pwp-ucr/),

* in FF I still get the JS error `TypeError: c[0] is undefined` coming from `https://www.w3.org/Tools/respec/respec-w3c-common`, and
* neither FF nor Chromium seem to be able to load and process the sourcemap.

Can you reproduce these errors, @marcoscaceres?

**Comment by halindrome** [comment]
I can confirm that people in the ARIA working group were reporting similar problems.  However, they were also reporting problems loading the HTML 51 spec from TR.  And that doesn't use respec at all.

**Comment by marcoscaceres** [comment]
@tripu, @halindrome, I've tried a few others specs and I think it's rdisplay and the other script that are causing the error. They seems to be touching parts of ReSpec likely before things have fully loaded. 

@halindrome, can you help me understand those scripts? I can help then integrate at the right points in the loading lifecycle (or maybe we can turn them into standard plugins?)

**Comment by iherman** [comment]
@marcoscaceres, it was not @halindrome that wrote those scripts, but I did. There is also a separate repo for the small family of scripts at https://github.com/iherman/respec-reqhandling

Without going into the details, in the UCR document there are two js files each defining their own methods: `rcollect` and `rdisplay`. The first one collects some information in the respec file and adds the results to a global variable, the second one uses the information collected in that global variable and displays it. The global variable is an array of objects, each object containing data about a requirement (id, number, definition, etc).

The reason of cutting the functionality into two is because (a) I can dump the content of a the array into a standalone js file that another respec file can load instead of `rcollect`, and that other file can just use `rdisplay` to display the content. (Ie, I can have another file cross referencing to requirements, with links and such.)

The way the functions are used by respec is to use `preProcess` and adding the two relevant method references in the corresponding array: `[rcollect, rdisplay]`. I may have been naïve, but my assumption is/was that these methods are executed not only at `preProcess` stage, but also sequentially. Is that assumption wrong, ie, may that be the reason of the problem? If so, how can I ensure that these functions are indeed executed sequentially without being forced to merge these into one file (which may make the organization a bit more complicated)? (I am not sure that an async execution for those methods in general would be warranted, b.t.w.)

All that being said, `rdisplay` is used, at this moment *only* in the UCR document. The problems did occur with other documents, as @halindrome also reported, although I am not sure those problems still persist.

**Comment by iherman** [comment]
B.t.w., I have just experiences a similar problem with:

https://rawgit.com/w3c/aria/dpub-cr/aria/dpub.html

which does not use the `rdisplay` script (though uses others).

**Comment by marcoscaceres** [comment]
Ok, sent a potential fix... seeing if TravisCI likes it

**Comment by marcoscaceres** [comment]
@iherman it's working for me now. Can you kindly please check on your end? Give it a good "shift-refresh" make sure the it's not using a cached version :) You can also check that the version is "6.1.1" in the "About respec..." option from the ReSpec pill.

**Comment by iherman** [comment]
> @iherman <https://github.com/iherman> it's working for me now. Can you kindly please check on your end? Give it a good "shift-refresh" make sure the it's not using a cached version :) You can also check that the version is "6.1.1" in the "About respec..." option from the ReSpec pill.
> 

I tried it both with the UCR document and the rawgit version of the ARIA document I reported on earlier this morning. Both work! (I was careful to make a complete reload and it is indeed 6.1.1 version for respec.)

Thanks!

**Comment by marcoscaceres** [comment]
Yay! thanks for confirming @iherman!

**Comment by iherman** [comment]
@marcoscaceres, I am sorry, but there is still a problem, although it seems to be a bit different.

I was careful to take a file that does not use any extra scripts, so I took 

http://w3c.github.io/dpub-pwp/

When I first load it the process does not complete; just like before the header is not generated, no TOC, etc. And no 'respec' button either, obviously. There is a difference between now and your latest change, though: while there was no styling at all before, some styling does occur this time insofar as the content is put into the narrow middle area and there is an empty space on the left that should contain the TOC. Except that it does not display the TOC or the header. Doing a simple reload get things working again. Once I have done a reload, I can reload it all over again and it will be all right. What is even more strange (to me) is that once it works in one browser (Opera is my main browser) it then works in Safari, Chrome, Firefox...

I also realized that I have the same effect on

https://rawgit.com/w3c/aria/dpub-cr/aria/dpub.html

my apologies to have pushed the reload button too early this morning. But that latter also uses a bunch of other scripts which may be misleading...

**Comment by marcoscaceres** [comment]
Confirmed... strange. Looking into it.

**Comment by marcoscaceres** [comment]
Ok, so now that the sourcemap is working, there something is accessing the UI before it has been created:

Uncaught TypeError: Cannot read property 'classList' of undefined
    at Object.show (ui.js:98)

**Comment by marcoscaceres** [comment]
As I'm not able to reproduce locally, I've put a temporary guard in place in ui.js... will hopefully let me figure out what is going on.

**Comment by marcoscaceres** [comment]
Ok, shipped in 6.1.2. It should at least not crash so badly. Please let me know if it keeps happening. It's a tricky one to reproduce.

**Comment by iherman** [comment]
> On 10 Nov 2016, at 08:06, Marcos Cáceres <notifications@github.com> wrote:
> 
> Ok, shipped in 6.1.2. It should at least not crash so badly. Please let me know if it keeps happening. It's a tricky one to reproduce.
> 

As you say, it is tricky to reproduce… 

I have tried it in Blink based clients (Opera, Brave, Vivaldi, Chrome), Firefox, and Safari, and they all worked. In some cases (Safari, FF) it still had the old respec in the cache and then it did not work, but after a complete reload (with respec 6.1.2) it did. Ie, it looks good...

**Comment by marcoscaceres** [comment]
I've not seen this come up anymore, so closing as WFM
